### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nene** [gaslight/atom-cucumber-step#20]
There hasn't been any development since Mar 31, 2016.

There are several pretty sensible looking pull requests that have been waiting with no feedback.

@superchris, in case you're not interested in developing this further, would you be interested in transferring the ownership of this atom package?

**Comment by nene** [comment]
I see there is already a fork [atom-behave-step](https://github.com/gdunn/atom-behave-step).

**Comment by nene** [comment]
Looks like the aforementioned `atom-behave-step` is a Python-specific fork that has dropped support for JavaScript and Ruby. So it's not really something to merge directly into this project.

Rather I would consider taking the unit-tests from `atom-behave-step` and re-implementing the Python support from scratch. If of course we'd like to have Python support in this package at all. But it looks like a sensible thing to have.

**Comment by nene** [comment]
I looked through all the open pull requests in here, and found that I would like to merge in each one of them. Perhaps not every change in all of them, but they all address a bug that needs fixing.

**Comment by nene** [comment]
Discovered another fork: [cucumber-step-jump](https://github.com/Drathal/atom-cucumber-step).

Created to merge in some PR-s that have been waiting too long in here.

I wonder if @Drathal is interested in developing this further or was this just one-off effort to get this package working.

**Comment by nene** [comment]
A-ha... From issue #14 I found this response from @superchris:

> We're not actually using cucumber much anymore, hence our lack of responsiveness on this repo. > Would you like to take it over?

But although @joost expressed desire to take the project over, @superchris did not follow up his response.

From this I can only conclude that the only feasible road forward is to fork. Not too keen to create another fork, my best bet right now is @Drathal.

**Comment by superchris** [comment]
Hey, actually, as it turns out I recently started on a project using Gherkin again. I'll look at merging all these PRs and doing a release today

**Comment by nene** [comment]
Wonderful!
