### ISSUE TITLE
Assumes Ruby

### ISSUE THREAD

**Issue by petey** [gaslight/atom-cucumber-step#6]
I'm writing tests with cucumber.js so obviously my step definitions don't end with `.rb`. Please add support to pick up step_definitions that have a `.js` suffix.

**Comment by jermspeaks** [comment]
Cucumber is written in Ruby, so it would make sense it wouldn't support the `.js` suffix. A step definitions generator for cucumber.js would be better as its own Atom.IO package, e.g. `atom-cucumberjs-step`.

**Comment by petey** [comment]
@jermspeaks That's a pretty poor response. What language the test runner executes in shouldn't make any difference here. By your logic, this plugin should have been written in Ruby. Both Gherkin and Regular Expressions are pretty language agnostic and that is all this plugin uses to find a step definition from a feature file. Ultimately this is already solved with https://github.com/gaslight/atom-cucumber-step/commit/beffdea65c6d51174c62571d7e61bdfb27997801.

**Comment by jermspeaks** [comment]
Thanks @petey. Can you explain that in a little more detail? What you're saying, so that I understand, is expressions should be language agnostic, or am I generalizing? If so, shouldn't there be more language support besides ruby and javascript?

**Comment by petey** [comment]
@jermspeaks Cucumber works by translating a Gherkin feature file to executable code through regular expression matching.

* Gherkin is a language independent DSL for writing feature files. For all intents and purposes, this is plain text. 
* Step definitions are essentially a set of regular expressions designed to match lines in the feature file in order to define the executable part of the test. Regular expressions are, for the most part, the same across all programing languages.

From what I've seen of this atom module, it is using a regular expression to discover where all the regular expressions are in all the files in `step_definitions` filtered on the file extension.  It then uses this collection of expressions to discover which file/line matches the line in gherkin matching cursor position.  

It is conceivable, to me, that this shouldn't necessarily need to have anything to do with the language implementation of the test runner, and there are plenty: https://cucumber.io/docs#cucumber-implementations, but I have only had experience with the Ruby and JS implementation.

**Comment by jermspeaks** [comment]
Thanks @petey for that clear explanation. :clap:
