### ISSUE TITLE
support of steps in javascript

### ISSUE THREAD

**Issue by benjamine** [gaslight/atom-cucumber-step#9]
I'm using cucumber.js (js port of cucumber) and I think it would be great (and not so hard) to support it too.
basically js steps are just .js files, where the step definition is pretty similar (not as pretty as a ruby DSL of course), but it could be found with a very similar regex.
I'll give it a try, would you be interested in a pull request?

**Comment by petey** [comment]
It looks like this has already been solved in commit https://github.com/gaslight/atom-cucumber-step/commit/beffdea65c6d51174c62571d7e61bdfb27997801

**Comment by benjamine** [comment]
it works indeed!, awesome, thanks
